### ISSUE TITLE
List of Cards

### ISSUE THREAD

**Issue by christofjens** [christofjens/lean-coffee-board#3]
# Value Proposition
As a **user**
I want to **have a list of the most frequent questions**
in order to **know that I did not miss anything**

# Description (text, scribble, wireframe, design
--> image.jpg <--

# Acceptance criteria
- [ ] Sorted alphabetically ascending

# Complexity (low, medium, high)
low

# Tasks
- [ ] Create feature branch
- [ ] Build card component (storybook)
- [ ] Test card component
- [ ] Add cards to app
- [ ] Add global styles
